[package]
name = "evilbocchi/alyanum"
version = "1.1.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "Alisa Mikhailovna \"Alya\" Kujou's go-to big number library for small and large-scale incremental games!"
license = "MIT"
include = ["AlyaNum", "AlyaNum/**", "default.project.json", "LICENSE", "wally.toml"]
exclude = ["*"]

[dependencies]
